### ISSUE TITLE
Only mobs with ABM spawn settings are spawning

### ISSUE THREAD

**Issue by mrkaczor83** [ElCeejo/animalia#27]
Hi, I am playing with mod and it worked without errors but I see only birds, bats and owls spawning. How can I fix settings to make animals spawn more often and to select types? I did digging in the code and it looks like in my world only spawn mobs with ABM spawning, so: rats, owls, frogs, birds, bats. Can I fix that?

I am running minetest with creatura, animalia and farming on 5.6.1 minetest from flatpack. Tested of old world and newly generated world.

**Comment by mrkaczor83** [comment]
I changed spawning to ABM for other mobs and now they works ... so thw issue is only with spawning itself

**Comment by ElCeejo** [comment]
All mobs use ABM spawning now.
