### ISSUE TITLE
Wrong MCL set_animation function

### ISSUE THREAD

**Issue by f3d0ss** [ElCeejo/animalia#31]
The MCL function to set the player animation is `player_set_animation`, the following two line cause the mod to crash.

https://github.com/ElCeejo/animalia/blob/21ad5faf7dfa7cd1cf64eadd8df6e6137695cf0f/api/api.lua#L112

https://github.com/ElCeejo/animalia/blob/21ad5faf7dfa7cd1cf64eadd8df6e6137695cf0f/api/behaviors.lua#L76

I will make a PR for this

**Comment by ElCeejo** [comment]
Fixed in latest update.
