### ISSUE TITLE
Knockback along the x and z axes seems to be getting cancelled by something

### ISSUE THREAD

**Issue by ma-choo** [ElCeejo/animalia#47]
I was messing with the knockback function trying to give mobs more substantial knockback. I can add plenty of velocity along the y axis, but there is no velocity along the x and z axes. If I set the velocity to an absurdly high number, they will move a great distance for a single frame before stopping.

I haven't had the chance to test it yet, but I'm assuming x and z velocity is being cancelled by the flee behavior in passive animals? Or perhaps even deeper in the creature:action_move function? I'm only guessing.

**Comment by ElCeejo** [comment]
Can't recreate this after the last commit.
