### ISSUE TITLE
Could not load image

### ISSUE THREAD

**Issue by dmeziere** [ElCeejo/animalia#57]
Hello,

First of all, installing minetest mods on a headless server seems poorly documented. I had to use curl to see the real archive URL, then wget to download it.

I downloaded creatura and animalia ZIP files and inflated it as /var/games/minetest-server/.minetest/mods/{creatura|animalia} and enabled it in the world.mt file.

The mods are working, and i see animals spawning, but without textures. The client is complaining about image creation. And i finally get kicked : "This server has experienced an internal error."

Is there a simple sollution ?

**Comment by ElCeejo** [comment]
Can't recreate this after the last commit.
