### ISSUE TITLE
libri animalia crashes the game

### ISSUE THREAD

**Issue by vonglahn** [ElCeejo/animalia#68]
Hi,

when I click on a animal with the libri I get a new topic in the book. But when I try to read the topic, the game just crashes.

**Comment by ElCeejo** [comment]
do you have a crash message?

**Comment by vonglahn** [comment]
Sorry I forgot. Here it is:

AsyncErr: Lua: Runtime error from mod 'animalia' in callback on_playerReceiveFields(): ...\minetest-5.8.0-win64\bin\..\mods\animalia/api/libri.lua:348: attempt to concatenate field 'text' (a nil value)
stack traceback:
	...\minetest-5.8.0-win64\bin\..\mods\animalia/api/libri.lua:348: in function 'render_element'
	...\minetest-5.8.0-win64\bin\..\mods\animalia/api/libri.lua:364: in function 'get_page'
	...\minetest-5.8.0-win64\bin\..\mods\animalia/api/libri.lua:490: in function <...\minetest-5.8.0-win64\bin\..\mods\animalia/api/libri.lua:481>
	...\minetest-5.8.0-win64\bin\..\builtin\common\register.lua:26: in function <...\minetest-5.8.0-win64\bin\..\builtin\common\register.lua:12>

**Comment by ElCeejo** [comment]
Should be resolved. Reopen if it persists after the latest commit.
