### ISSUE TITLE
could not load image, dummy image created

### ISSUE THREAD

**Issue by AmyMoriyama** [ElCeejo/animalia#7]
EDIT: copying textures from their folder into the main textures/ folder fixes this. I also noticed no sounds, copying sounds from their respective folders to the main sounds/ folder fixes this too.

Installed the latest git on my server and every animal is a dummy image.

![screenshot_20210825_155015](https://user-images.githubusercontent.com/87048190/130855924-3cd91c76-f24e-40f6-bc64-3ecbdf00a955.png)

**Comment by ElCeejo** [comment]
This is only an issue on pre-5.4 clients, which the mod is not officially compatible with.

**Comment by StoyanDimitrov** [comment]
Clients or servers? I'm running 5.4.1 client and am able to reproduce the issue.
