### ISSUE TITLE
Issue when loading in worlds after new release

### ISSUE THREAD

**Issue by DustyBagel** [ElCeejo/animalia#70]
When I enter my world I get this error message:
AsyncErr: Lua: Runtime error from mod 'animalia' in callback luaentity_Activate(): ...-5.8.0-win64-release\bin\..\mods\animalia/mobs/horse.lua:154: attempt to index local 'colors' (a nil value)
2023-12-30 05:08:47: ERROR[Main]: stack traceback:
2023-12-30 05:08:47: ERROR[Main]:       ...-5.8.0-win64-release\bin\..\mods\animalia/mobs/horse.lua:154: in function 'set_pattern'
2023-12-30 05:08:47: ERROR[Main]:       ...-5.8.0-win64-release\bin\..\mods\animalia/mobs/horse.lua:365: in function 'activate_func'
2023-12-30 05:08:47: ERROR[Main]:       ...st-5.8.0-win64-release\bin\..\mods\creatura/mob_meta.lua:889: in function <...st-5.8.0-win64-release\bin\..\mods\creatura/mob_meta.lua:773>
I will continue to look into this myself so I can find a fix or better describe how to recreate the crash.

**Comment by vonglahn** [comment]
Get this error from time to time.

**Comment by DustyBagel** [comment]
@vonglahn  What do you mean by that?

**Comment by vonglahn** [comment]
@DustyBagel I had area that threw that error as soon a I entered it. I had to disable animalia to start the word again.

I solved It by using the cleaner mod to remove all animalia:horses in that area.

**Comment by DustyBagel** [comment]
@vonglahn How did you do that? I just downloaded the previous release of the mod.

**Comment by vonglahn** [comment]
No I use the current release. For now, I deactivate spawning of mods in the settings and hope that it will befixed soon.

**Comment by vonglahn** [comment]
And for removing the entities I uses the mod "cleaner" like this "/remove_entities animalia:horse 100"

**Comment by ElCeejo** [comment]
Latest commit should fix this but I haven't been able to test it myself.

**Comment by DustyBagel** [comment]
The world doesn't crash anymore but can't get on the horses or interact with them other than punching them.

**Comment by ElCeejo** [comment]
Fixed I think
