### ISSUE TITLE
Little character

### ISSUE THREAD

**Issue by PavanLuca** [ElCeejo/animalia#71]
This is like dragonfly-ai's issue report about giant character riding horses but in my case it's small. Happens by switching to another horse while already riding one. You may see a small different pixel on the back of 2 horses, it's the character. On a screenshot it's either invisible or simply became a pixel.
![Schermata da 2024-01-04 12-49-15](https://github.com/ElCeejo/animalia/assets/123581658/8844c13c-b18c-4e01-8680-64a2f6296a72)
![Schermata da 2024-01-04 12-49-03](https://github.com/ElCeejo/animalia/assets/123581658/1d195329-780e-4811-b8a2-2f7584e71a50)
![Schermata da 2024-01-04 12-48-13](https://github.com/ElCeejo/animalia/assets/123581658/4b77741e-a857-4a7a-aa20-1c4923600fb1)
![Schermata da 2024-01-04 12-48-27](https://github.com/ElCeejo/animalia/assets/123581658/b7035b04-a54e-4dcf-b9b5-725eb86050fa)
![Schermata da 2024-01-04 12-48-38](https://github.com/ElCeejo/animalia/assets/123581658/22b8b9fa-59af-4516-a812-95476c661546)
![Schermata da 2024-01-04 12-48-53](https://github.com/ElCeejo/animalia/assets/123581658/7eb7b733-f076-44e5-a89c-df4d01b44828)

**Comment by ElCeejo** [comment]
Latest update stops players from mounting another horse while already on one. Reopen if the issue persists.
