### ISSUE TITLE
Horse mounting bug

### ISSUE THREAD

**Issue by baloozabear** [ElCeejo/animalia#77]
I love the mod and it used to work great but after the new update it won't let me mount any horses to tame them and I'm pretty sure the problem isn't my device because none of my other mods are lagging and it's `definetly` not my server because i tried it in single player mode with no other mods in a different server and it still wouldn't work. I tried updating it and updating creatura but no luck.

**Comment by JaedonV** [comment]
Exact same thing is happening to me and my server.

**Comment by ElCeejo** [comment]
Should be fixed
