### ISSUE TITLE
horse scaling issues.

### ISSUE THREAD

**Issue by dragonfly-ai** [ElCeejo/animalia#9]
![Screenshot from 2021-12-03 21-44-54](https://user-images.githubusercontent.com/24378760/144762440-95a966e6-3abe-4e33-9acb-284b1d3a5ce7.png)

For some reason horseback riding coincides with a dramatic increase in the scale of the player's character model.

**Comment by CloudyProton** [comment]
Arrows shot at Animalia mobs using TechAI's bows mod also sees arrows grow several times in size when they attach to mobs.

**Comment by ElCeejo** [comment]
Fixed.
